# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('djangocms_alias', '0002_auto_20200327_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set([('identifier', 'site')]),
        ),
    ]
